#trigger:
- task: Maven@4
  inputs:
    azureSubscription: 'Free Trial(2cdb0d88-48b8-4743-bc11-1e17d8622e79)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    allowBrokenSymlinks: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
#- main
stages:
- stage: BuildandPublishArtifact
  jobs:
  - job: Build
    pool:
      name: test pool
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target/'
        Contents: 'perseverance.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'